version: "3.9"

services:
  model_service:
    build:
      context: .
      dockerfile: Dockerfile.model
    container_name: model_service
    env_file:
      - .env
    environment:
      GGUF_MODEL_PATH: /app/models/model-q2_k.gguf
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./docs:/app/docs:ro
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health | grep '\"status\": \"ok\"' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    env_file:
      - .env
    environment:
      MODEL_SERVICE_URL: http://model_service:8000
    depends_on:
      model_service:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./docs:/app/docs:ro
      - ./data:/app/data
    restart: unless-stopped 